import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createHash} from 'node:crypto';
import {accountApi,accountTables,deviceOwner,issueDevice,hash} from '../lib/server/accounts';
test('desktop grants require PKCE, expire, and cannot be replayed; devices are account isolated',async()=>{
  const db=new DatabaseSync(':memory:');await accountTables(db);
  db.exec('CREATE TABLE conversations(id TEXT PRIMARY KEY,owner TEXT,data TEXT)');
  const keys=new Map();const d={db,active:new Set<string>(),providers:['groq'],readKey:(o:string,p:string)=>keys.get(o+':'+p)||null,writeKey:(o:string,p:string,k:string|null)=>{keys.set(o+':'+p,k?{apiKey:k,accountId:null}:null);}};
  const call=(path:string,owner:string|null,body?:unknown,token='')=>accountApi(new Request('http://localhost:3000/api/account/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token},body:body===undefined?undefined:JSON.stringify(body)}),['account',path],owner,d);
  const verifier='x'.repeat(43),challenge=createHash('sha256').update(verifier).digest('base64url');
  const grantBody={challenge,state:'s'.repeat(43),callback:'http://127.0.0.1:12345/callback'};
  assert.equal((await call('desktop-authorizations','alice',{...grantBody,callback:'https://evil.example/callback'}))?.status,400);
  const grant=await (await call('desktop-authorizations','alice',grantBody))!.json();const code=new URL(grant.callback).searchParams.get('code');
  assert.equal((await call('desktop-token',null,{code,verifier:'y'.repeat(43)}))?.status,401);
  const session=await (await call('desktop-token',null,{code,verifier}))!.json();assert.equal(await deviceOwner(db,session.token),'alice');
  assert.equal((await call('desktop-token',null,{code,verifier}))?.status,401);
  assert.equal((await call('sync','alice',{changes:[]}))?.status,403);
  assert.equal((await call('sync','bob',{changes:[]},session.token))?.status,403);
  assert.equal((await call('sync','alice',{changes:[{kind:'provider',id:'groq',base:null,value:{apiKey:'fixture-provider-secret',accountId:null}}]},session.token))?.status,403);
  const bob=await issueDevice(db,'bob','test');const result=await (await call('sync','bob',{changes:[]},bob))!.json();assert(!result.records.some((r:any)=>r.kind==='provider'));assert(!JSON.stringify(result).includes('fixture-provider-secret')); 
  const chat={id:'c1',title:'Original',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),messages:[]};
  await call('sync','alice',{changes:[{kind:'chat',id:'c1',base:null,value:chat}]},session.token);
  const conflict=await (await call('sync','alice',{changes:[{kind:'chat',id:'c1',base:null,value:{...chat,title:'Overwrite'}}]},session.token))!.json();assert.deepEqual(conflict.conflicts,['chat:c1']);assert.equal(conflict.records.find((r:any)=>r.id==='c1').value.title,'Original');
  assert.equal((await call('sync','bob',{changes:[{kind:'chat',id:'c1',base:null,value:chat}]},bob))?.status,400);
  await call('sync','alice',{changes:[{kind:'chat',id:'c1',base:hash(JSON.stringify(chat)),value:null}]},session.token);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM sync_deleted').get()!.n,1);
  await call('revoke','bob',{id:hash(session.token)});assert.equal(await deviceOwner(db,session.token),'alice');
  await call('revoke','alice',{id:hash(session.token)});assert.equal(await deviceOwner(db,session.token),null);
  const expired=await issueDevice(db,'alice','expired');db.prepare('UPDATE device_sessions SET expires=0 WHERE hash=?').run(hash(expired));assert.equal(await deviceOwner(db,expired),null);db.close();
});
