'use client';
import { ManagedAccount } from './managed-account';
import { useEffect, useState } from 'react';
import { getAuthToken } from '@/lib/cloud-api/custom-fetch';
export function DesktopConnect(){
  const [error,setError]=useState(''),[pending,setPending]=useState(false);
  async function connect(){setPending(true);setError('');try{const params=new URLSearchParams(location.search);const response=await fetch('/api/account/'+(params.get('platform')==='android'?'android-authorizations':'desktop-authorizations'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+await getAuthToken()},body:JSON.stringify({challenge:params.get('challenge'),callback:params.get('callback'),state:params.get('state')})});const data=await response.json();if(!response.ok)throw new Error(data.error);const target=new URL(data.callback);const requested=new URL(params.get('callback')||'');if(target.origin!==requested.origin||target.pathname!==requested.pathname||target.searchParams.get('state')!==params.get('state'))throw new Error('Invalid connection callback.');location.assign(target.href);}catch(e){setError(e instanceof Error?e.message:'Connection failed.');setPending(false);}}
  return <div className="desktop-login"><div className="desktop-login-card"><img src="/brand/swarm-wordmark.png" width="110" alt="SWARM"/><h1>Connect your device</h1><p>Connect this account’s chats, managed AI access and preferences to your device.</p><button className="desktop-login-guest" disabled={pending} onClick={()=>void connect()}>{pending?'Connecting…':'Connect SWARM'}</button>{error&&<p role="alert">{error}</p>}</div></div>;
}
export function AccountPanel(){
  const [account,setAccount]=useState<{email:string|null;role:string;name?:string|null;avatar?:string|null}|null>(null),[devices,setDevices]=useState<{id:string;name:string;expires:number}[]>([]),[error,setError]=useState('');
  async function call(path:string,body?:unknown){const r=await fetch('/api/account/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+await getAuthToken(),...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}
  async function load(){try{setAccount(await call('profile'));setDevices((await call('devices')).devices);}catch(e){setError(e instanceof Error?e.message:'Account could not load.');}}
  useEffect(()=>{void load();},[]);
  return <section className="account-workspace"><ManagedAccount/><div className="account-identity"><h2 className="font-semibold">Account & sync</h2><p className="text-sm">{account?.avatar&&<img src={account.avatar} alt="" className="h-10 w-10 rounded-full inline-block mr-3"/>}{account?.name&&<strong>{account.name} · </strong>}{account?.email||'Your SWARM account'} {account?.role==='owner'&&<span className="ml-2 text-xs text-blue-600">Owner · Administrator</span>}</p><p className="text-xs text-muted-foreground">Your chats and managed AI access belong to this account. Sign in from the desktop’s Account settings to sync them.</p>{devices.map(d=><div key={d.id} className="account-device-row"><span>{d.name}</span><button className="text-blue-600" onClick={()=>void call('revoke',{id:d.id}).then(load).catch(e=>setError(e.message))}>Disconnect</button></div>)}{!devices.length&&<p className="text-xs text-muted-foreground">No connected desktop devices.</p>}{error&&<p className="sw-error" role="alert">{error}</p>}</div></section>;
}
