'use client';
import { type RefObject } from 'react';
import { Check, Sparkles, X, CreditCard, ShieldCheck, Receipt } from 'lucide-react';
import { Button, Usage, Status, SectionHeader, EmptyState, Loading } from './design-system';
import { formatBillingDate, formatPrice } from './presentation';

type Props={paymentNotice:string;state:any;history:any[];error:string;busy:boolean;compact:boolean;phone:string;setPhone:(s:string)=>void;setUpgradeOpen:(v:boolean)=>void;dialogRef:RefObject<HTMLDialogElement|null>;retry:()=>void;action:(fn:()=>Promise<void>)=>Promise<void>;load:()=>Promise<void>;verify:(id:string)=>Promise<void>;upgrade:()=>Promise<void>;preferences:(profile:string,speed:string)=>Promise<void>};
export function BillingView({paymentNotice,state,history,error,busy,compact,phone,setPhone,setUpgradeOpen,dialogRef,retry,action,load,verify,upgrade,preferences}:Props){
  const price=state?formatPrice(state.catalog?.pro?.price,state.catalog?.pro?.currency||'INR'):'Amount unavailable';
  return <section className={`billing-workspace ${compact?'billing-compact':''}`} aria-label="SWARM plan and usage">
    {!state?(error?<div className="sw-error" role="alert"><p>{error}</p><Button disabled={busy} onClick={retry}>Retry</Button></div>:<Loading label="Loading your plan…"/>):<>
      <div className="billing-plan-heading"><div><span className="sw-eyebrow">YOUR SUBSCRIPTION</span><h2>{state.unlimited?'SWARM Unlimited':state.plan.id==='pro'?'SWARM Pro':'SWARM Free'}</h2></div><Status tone="success">{state.unlimited?'Unlimited access':state.plan.id==='pro'?'Pro access':'Free plan'}</Status>{!state.unlimited&&<Button variant="primary" onClick={()=>setUpgradeOpen(true)}><Sparkles size={14}/>{state.plan.id==='pro'?'Renew Pro':'Explore Pro'}</Button>}</div>
      <div className="billing-usage-grid"><Usage label="Build allowance" used={state.builds?.used} limit={state.builds?.limit} unlimited={state.unlimited}/><Usage label="Chat allowance" used={state.chats?.used} limit={state.chats?.limit} unlimited={state.unlimited}/></div>
      {!state.unlimited&&<p className="billing-reset">{formatBillingDate(state.resetsAt)==='Date unavailable'?'Reset schedule unavailable':'Next reset · '+formatBillingDate(state.resetsAt)}{state.plan.id==='pro'?' · Pro access ends '+formatBillingDate(state.account.pro_until):''}</p>}
      <details className="billing-model-controls" open={!compact}><summary>Model & generation preferences <span>{state.account.profile} · {state.account.speed}</span></summary><div><label>Model profile<select disabled={busy} value={state.account.profile} onChange={e=>{const p=state.profiles.find((p:any)=>p.id===e.target.value);if(!p?.eligible){setUpgradeOpen(true);return;}void action(()=>preferences(e.target.value,state.account.speed));}}>{(state.profiles||[]).map((p:any)=><option key={p.id} value={p.id} disabled={!p.available}>{p.name}{!p.eligible?' · Unlock with Pro':!p.available?' · unavailable':''}</option>)}</select></label><label>Generation<select disabled={busy} value={state.account.speed} onChange={e=>{if(e.target.value==='fast'&&!state.plan.premium){setUpgradeOpen(true);return;}void action(()=>preferences(state.account.profile,e.target.value));}}>{['fast','balanced','quality'].map(v=><option key={v} value={v}>{v==='fast'&&!state.plan.premium?'Fast · Unlock with Pro':v}</option>)}</select></label></div></details>
      {!compact&&<>
        <SectionHeader title="Built for your next idea" description="Managed AI access across web, desktop, and Android. Your prompts are processed by configured AI providers."/>
        <div className="billing-benefits"><ShieldCheck size={20}/><div><strong>One account. A connected workspace.</strong><p>Automatic model routing, shared conversations, and synchronized preferences. Pro adds speed-first routing and more room to create.</p></div></div>
        {!state.checkoutAvailable&&<p className="sw-notice" role="status">Checkout is awaiting merchant or fair-use configuration.</p>}
        <SectionHeader title="Transaction history" description="Payment records and verification status from your account."/>
        {!history.length?<EmptyState icon={<Receipt size={22}/>} title="No transactions yet" description="Your payment records will appear here after you start a checkout."/>:<div className="transaction-table"><table><thead><tr><th>Transaction</th><th>Amount</th><th>Date</th><th>Status</th></tr></thead><tbody>{history.map(t=><tr key={t.id}><td><details><summary>{t.id}</summary><div><p>Payment reference: {t.payment||'Not available'}</p>{t.status!=='paid'&&<Button disabled={busy} onClick={()=>void action(()=>verify(t.id))}>Check payment status</Button>}</div></details></td><td>{formatPrice(t.amount,t.currency||'INR')}</td><td>{formatBillingDate(t.created)}</td><td><Status tone={t.status==='paid'?'success':t.status==='failed'?'error':t.status==='cancelled'?'neutral':'warning'}>{t.status||'Unavailable'}</Status></td></tr>)}</tbody></table></div>}
      </>}
    </>}
    {paymentNotice&&<p className="sw-notice" role="status">{paymentNotice}</p>}
    {error&&state&&<div className="sw-error" role="alert">{error} <Button disabled={busy} onClick={()=>void action(load)}>Retry</Button></div>}
    {state&&<dialog ref={dialogRef} onCancel={()=>setUpgradeOpen(false)} onClose={()=>setUpgradeOpen(false)} aria-labelledby="upgrade-title" className="sw-dialog upgrade-dialog">
      <header><div><span className="sw-eyebrow">A LITTLE MORE ROOM</span><h2 id="upgrade-title">Keep your ideas moving.</h2></div><Button variant="ghost" aria-label="Close upgrade" onClick={()=>setUpgradeOpen(false)}><X size={18}/></Button></header><p>Choose the capacity that fits your work. Renew when you need it.</p>
      <div className="plan-comparison"><section className="sw-plan"><h3>Free</h3><p className="sw-price">₹0 <small>to get started</small></p><ul>{[`${state.catalog.free.builds??'Unavailable'} builds per ${state.catalog.free.days} days`,`${state.catalog.free.chats??'Unavailable'} chats per ${state.catalog.free.days} days`,'Balanced automatic routing','Web, desktop and Android'].map(v=><li key={v}><Check size={15}/>{v}</li>)}</ul><Status>{state.plan.id==='free'?'Your current plan':'Free plan'}</Status></section><section className="sw-plan sw-plan-featured"><div className="sw-plan-title"><h3>Pro</h3><Sparkles size={18}/></div><p className="sw-price">{price}<small>/ {state.catalog.pro.accessDays} days</small></p><ul>{[`${state.catalog.pro.builds??'Unavailable'} builds per ${state.catalog.pro.days} days`,`${state.catalog.pro.chats??'Unavailable'} chats per ${state.catalog.pro.days} days`,'SWARM SWE Fast routing',`${state.catalog.pro.concurrency} simultaneous requests`,'Manual renewal; no automatic charges'].map(v=><li key={v}><Check size={15}/>{v}</li>)}</ul><p className="sw-plan-note">Eligible models and response speed depend on provider capacity.</p></section></div>
      <section className="checkout-summary" aria-label="Checkout summary"><div><strong>SWARM Pro · {state.catalog.pro.accessDays} days</strong><strong>{price}</strong></div><p><ShieldCheck size={14}/> Access begins after server-verified payment. Review final details in Cashfree.{state.billingMode==='sandbox'?' Test checkout: no live charge.':''}</p><label htmlFor="checkout-phone">Indian mobile number</label><div className="phone-field"><span>+91</span><input id="checkout-phone" aria-label="Checkout mobile number" aria-describedby="phone-help" aria-invalid={phone.length>0&&!/^[6-9][0-9]{9}$/.test(phone)} type="tel" autoComplete="tel-national" inputMode="numeric" value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,''))} maxLength={10} placeholder="10-digit mobile number"/></div><small id="phone-help">{phone.length>0&&!/^[6-9][0-9]{9}$/.test(phone)?'Enter 10 digits starting with 6, 7, 8, or 9.':'Cashfree requires a mobile number for this payment.'}</small><Button variant="primary" disabled={busy||!state.checkoutAvailable||!/^[6-9][0-9]{9}$/.test(phone)} onClick={()=>void action(upgrade)}><CreditCard size={16}/>{busy?'Processing checkout…':'Continue to secure checkout'}</Button>{!state.checkoutAvailable&&<p role="status">Payments are temporarily unavailable. Try again later.</p>}{error&&<p className="sw-error" role="alert">{error}</p>}</section>
    </dialog>}
  </section>;
}
