'use client';
import {useEffect,useState} from 'react';
import {Globe2,Monitor,Smartphone,Tablet,RotateCw,AlertCircle} from 'lucide-react';
import {customFetch} from '@/lib/cloud-api/custom-fetch';
export function ProjectPreview({id,version}:{id:string|null;version:string}) {
  const [vp,setVp]=useState<'desktop'|'tablet'|'mobile'>('desktop'),[html,setHtml]=useState(''),[entry,setEntry]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[reload,setReload]=useState(0);
  useEffect(()=>{let alive=true;setHtml('');setError('');if(!id)return;setLoading(true);void customFetch<{html:string;entry:string}>('/api/conversations/'+encodeURIComponent(id)+'/preview',{method:'POST',body:'{}',responseType:'json'}).then(result=>{if(alive){setHtml(result.html);setEntry(result.entry);}}).catch(e=>{if(alive)setError(e?.data?.error||'This project is not ready for a browser preview.');}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[id,version,reload]);
  return <div className="web-runtime-preview"><div className="web-runtime-toolbar"><Globe2 size={14}/><span>{entry||'Project preview'}</span><div role="group" aria-label="Preview viewport">{([['desktop',Monitor],['tablet',Tablet],['mobile',Smartphone]] as const).map(([value,Icon])=><button key={value} aria-label={value+' preview'} aria-pressed={vp===value} onClick={()=>setVp(value)}><Icon size={15}/></button>)}</div><button aria-label="Reload preview" disabled={loading||!id} onClick={()=>setReload(n=>n+1)}><RotateCw size={14}/></button></div><div className="web-runtime-viewport">{html?<iframe key={reload} title="Generated project preview" sandbox="allow-scripts" referrerPolicy="no-referrer" srcDoc={html} style={{width:vp==='mobile'?390:vp==='tablet'?768:'100%'}}/>:<div className="web-runtime-empty"><AlertCircle size={22}/><strong>{loading?'Preparing your preview…':'Project preview'}</strong><p>{error||'The generated project appears here after its files are ready.'}</p></div>}</div></div>;
}
