'use client';
import {useState} from 'react';
import Link from 'next/link';
import {ArrowUpRight,Check,FileCode2,Workflow,MessageSquare,Folder,ChevronRight,Code2,ShieldCheck,Package,Lightbulb} from 'lucide-react';
const steps=[{name:'Planner',label:'A clear starting point',icon:Lightbulb,detail:'Define the pages, file structure, and interactions before writing the code.'},{name:'Coder',label:'Ideas become files',icon:Code2,detail:'Create complete project files with the structure you need to keep building.'},{name:'Reviewer',label:'A second perspective',icon:ShieldCheck,detail:'Review the draft for missing details and improve the final response.'},{name:'Finalizer',label:'Ready to take with you',icon:Package,detail:'Package the generated files. Download a single file or the whole project as a ZIP.'}];
export function BuildPreview(){
  const [selected,setSelected]=useState(1);const step=steps[selected];
  return <div className="build-showcase"><div className="build-showcase-bar"><div><img src="/swarm-icon.png" alt=""/><b>SWARM</b></div><span><MessageSquare size={14}/> Chat <i><Workflow size={14}/> Build</i></span><small>WORKSPACE PREVIEW</small></div>
    <div className="build-showcase-body"><div className="build-showcase-canvas"><span className="build-showcase-eyebrow">ONE IDEA. A TEAM TO BUILD IT.</span><h3>Your next idea,<br/><em>connected.</em></h3><p>A personal portfolio with a project gallery.</p><div className="build-showcase-graph"><svg viewBox="0 0 580 235" preserveAspectRatio="none" aria-hidden="true"><path d="M145 60 C230 60 220 175 290 175 S350 60 435 60"/></svg>{steps.map((s,i)=><button key={s.name} className={`build-showcase-node graph-node-${i} ${selected===i?'is-selected':''}`} onClick={()=>setSelected(i)} aria-pressed={selected===i}><span className="build-node-icon"><s.icon size={18}/></span><b>{s.name}</b><small>{['Plan the project','Create the code','Review the draft','Package the files'][i]}</small><span className="build-node-index">0{i+1}<ChevronRight size={12}/></span></button>)}</div><span className="build-showcase-hint">Select a step to explore the workflow.</span></div>
    <aside className="build-showcase-inspector"><div className="build-inspector-title"><step.icon size={18}/><span>{step.name}</span><span className="build-example-badge">Example</span></div><h4>{step.label}</h4><p>{step.detail}</p><div className="build-showcase-files"><span><Folder size={14}/> portfolio</span>{['index.html','styles.css','app.js','README.md'].map(name=><div key={name}><FileCode2 size={14}/>{name}</div>)}</div><div className="build-showcase-package"><Package size={20}/><div><b>Make it yours.</b><small>Individual files + project ZIP</small></div><Check size={16}/></div><Link className="build-showcase-launch" href={'/app?mode=build&prompt='+encodeURIComponent('Build a personal portfolio website with a project gallery, responsive layout, and a soft blue accent. Include all files needed to run it.')}>Start your own build <ArrowUpRight size={16}/></Link></aside></div>
  </div>;
}
