'use client';
import {BuildPreview} from './build-preview';
import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { MissionStarter } from './mission-starter';
import { ArrowDown, ArrowUpRight, Download, Monitor, Smartphone } from 'lucide-react';

const minds=[['Strategist','Shapes a clear direction.'],['Researcher','Finds and synthesizes context.'],['Designer','Gives the idea its form.'],['Builder','Turns a plan into code.'],['Reviewer','Checks and refines the result.'],['Operator','Coordinates the next step.']];
export function CinematicHome(){
  const story=useRef<HTMLElement>(null);const [selected,setSelected]=useState(0);
  useEffect(()=>{const root=story.current;if(!root)return;const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');let frame=0;const animate=()=>{if(reduce.matches)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const rect=root.getBoundingClientRect();root.style.setProperty('--story-progress',String(Math.max(0,Math.min(1,-rect.top/(rect.height-window.innerHeight)))));});};window.addEventListener('scroll',animate,{passive:true});animate();const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.target.classList.toggle('in-view',entry.isIntersecting)),{threshold:.15});root.querySelectorAll('.story-reveal').forEach(el=>observer.observe(el));return()=>{observer.disconnect();window.removeEventListener('scroll',animate);cancelAnimationFrame(frame);};},[]);
  return <main className="cinematic-home" ref={story}>
    <section className="cinema-hero">
      <div className="cinema-title"><span className="cinema-eyebrow">SWARM AI / A COLLECTIVE INTELLIGENCE</span><h1>ONE MISSION.<br/><span>MANY MINDS.</span></h1><p>Specialized AI agents. One shared direction.<br/>A workspace that takes your ideas further.</p><div className="cinema-actions"><Link href="/app" className="cinema-button">Launch SWARM <ArrowUpRight size={17}/></Link><a href="#intelligence" className="cinema-text-link">Explore SWARM <ArrowDown size={16}/></a></div></div>
      <MissionStarter/>
    </section>
    <section id="intelligence" className="cinema-intelligence cinema-section story-reveal"><div className="cinema-editorial"><span className="cinema-eyebrow">02 / A DIFFERENT WAY TO WORK</span><h2>One AI can answer.<br/><span>A swarm can accomplish.</span></h2><p>A complex idea needs more than one perspective. SWARM brings specialized capabilities around a single mission.</p></div><div className="spatial-minds" aria-label="Explore SWARM capabilities"><div className="spatial-rings"/><div className="spatial-core"><img src="/swarm-icon.png" alt="SWARM intelligence core"/></div>{minds.map(([name,description],i)=><button key={name} className={`spatial-node node-${i} ${selected===i?'selected':''}`} onMouseEnter={()=>setSelected(i)} onFocus={()=>setSelected(i)} onClick={()=>setSelected(i)} aria-pressed={selected===i}><span className="node-sphere"/><span>{name}</span></button>)}<div className="mind-description" aria-live="polite"><b>{minds[selected][0]}</b><p>{minds[selected][1]}</p></div></div></section>
    <section className="cinema-workflow cinema-section story-reveal"><span className="cinema-eyebrow">03 / FROM IDEA TO EXECUTION</span><div className="cinema-editorial"><h2>Your idea.<br/><span>A shared plan.<br/>Something real.</span></h2><p>Build mode plans the project, creates the code, and reviews the result. Follow each step in the live graph. Keep individual files or download the entire project.</p><Link className="cinema-text-link" href="/app?mode=build">Start a build <ArrowUpRight size={17}/></Link></div><div className="execution-object" aria-label="Build workflow"><div className="execution-axis"/>{['Plan','Build','Review','Deliver'].map((label,i)=><div className="execution-step" key={label}><span>0{i+1}</span><div className={`execution-orb orb-${i}`}/><strong>{label}</strong></div>)}<div className="execution-result"><span>YOUR PROJECT</span><strong>Ready to make your own.</strong><span>FILES / ZIP</span></div></div></section>
    <section className="cinema-control cinema-section story-reveal"><span className="cinema-eyebrow">04 / ALWAYS YOUR MISSION</span><h2>You're still<br/><span>in control.</span></h2><div><p>Direct the mission. Shape the outcome.<br/>Let specialized minds handle the work.</p><p className="cinema-small">Choose Auto or a specific model. Edit a request, stop a response, and review the code before using it.</p><Link className="cinema-text-link" href="/app/settings">Your models. Your providers. <ArrowUpRight size={17}/></Link></div></section>
    <section className="cinema-product cinema-section story-reveal"><div className="product-heading"><span className="cinema-eyebrow">05 / ENTER THE WORKSPACE</span><h2>Meet your next<br/><span>working environment.</span></h2><Link className="cinema-button" href="/app?mode=build">Launch SWARM <ArrowUpRight size={17}/></Link></div><BuildPreview/></section>
    <section className="cinema-download cinema-section story-reveal" id="download"><span className="cinema-eyebrow">06 / TAKE SWARM WITH YOU</span><h2>At your desk.<br/><span>In your pocket.</span></h2><div className="download-options"><div><Monitor size={27} strokeWidth={1.3}/><h3>SWARM for Windows</h3><p>The desktop workspace for your next mission.</p><a href="/downloads/SWARM-AI-Setup.exe" download className="cinema-button">Download for Windows <Download size={16}/></a><small>Windows 10 / 11 · Account sync included</small></div><div><Smartphone size={27} strokeWidth={1.3}/><h3>SWARM for Android</h3><p>Your SWARM companion, wherever you are.</p><a href="/downloads/SWARM-AI.apk" download className="cinema-button">Download APK <Download size={16}/></a><small>Android 8.0+ · Development build</small></div></div></section>
    <section className="cinema-finale story-reveal"><img src="/swarm-icon.png" alt="" loading="lazy"/><span className="cinema-eyebrow">LET THEM WORK TOGETHER.</span><h2>ONE MISSION.<br/><span>MANY MINDS.</span></h2><Link className="cinema-button" href="/app">Launch SWARM <ArrowUpRight size={17}/></Link></section>
  </main>;
}

