'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import { CinematicHome } from './cinematic-home'
import { ArrowUpRight, Check, Command, Menu, Plus, Search, X, Zap } from 'lucide-react'

const logo = '/swarm-icon.png'
const wordmark = '/brand/swarm-wordmark.png'
const agents = [
  ['Strategist','Shapes the mission','S'],['Researcher','Finds the signal','R'],['Builder','Makes it real','B'],['Designer','Gives it form','D'],['Reviewer','Raises the bar','V'],['Operator','Keeps it moving','O'],
]
const missions = ['Launch website','Research competitors','Build mobile app','Analyze dataset']
function Mark({ word = false }: { word?: boolean }) { return <img className={word ? 'logo wordmark' : 'logo'} src={word ? wordmark : logo} alt="SWARM AI" /> }
function CTA({ children, href='/app', light=false }: { children: React.ReactNode; href?: string; light?: boolean }) { return <Link className={`cta ${light ? 'light' : ''}`} href={href}>{children}<ArrowUpRight /></Link> }

function Nav() {
  const [open,setOpen] = useState(false); const [scrolled,setScrolled] = useState(false)
  useEffect(() => { const onScroll=()=>setScrolled(window.scrollY>20); window.addEventListener('scroll',onScroll,{passive:true}); return()=>window.removeEventListener('scroll',onScroll) },[])
  const links=[['Agents','/agents'],['Platform','/platform'],['Cloud','/cloud'],['How it works','/how-it-works'],['Download','/#download'],['Pricing','/pricing']]
  return <header className={`nav ${scrolled?'scrolled':''}`}><Link href="/" className="brand"><Mark word /><span>SWARM AI</span></Link><nav className={open?'open':''}>{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href="/login" onClick={()=>setOpen(false)}>Log in</Link><CTA>Launch SWARM</CTA></nav><div className="nav-right"><Link href="/login">Log in</Link><CTA>Launch SWARM</CTA><button className="menu" onClick={()=>setOpen(!open)} aria-label={open?"Close navigation":"Open navigation"} aria-expanded={open}>{open?<X/>:<Menu/>}</button></div></header>
}

function CommandPalette() { const [show,setShow]=useState(false);const [query,setQuery]=useState(''); useEffect(()=>{const f=(e:KeyboardEvent)=>{if(e.key==='Escape')setShow(false);if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setShow(v=>!v)} }; window.addEventListener('keydown',f); return()=>window.removeEventListener('keydown',f)},[]); if(!show)return null; const items=[['Agents','/agents'],['Platform','/platform'],['Cloud','/cloud'],['Open App','/app'],['Documentation','/documentation'],['Settings','/app/settings']].filter(([label])=>label.toLowerCase().includes(query.toLowerCase())); return <div className="palette-backdrop" onClick={()=>setShow(false)}><div className="palette" role="dialog" aria-modal="true" aria-label="Search SWARM" onClick={e=>e.stopPropagation()}><div className="palette-search"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search SWARM"/><button aria-label="Close search" onClick={()=>setShow(false)}>ESC</button></div>{items.map(([x,h])=><Link key={h} href={h} onClick={()=>setShow(false)}><Command/><span>{x}</span><ArrowUpRight/></Link>)}{!items.length&&<p>No matching pages.</p>}</div></div> }

function MissionControl({ compact=false }: { compact?: boolean }) { const router=useRouter();const [active,setActive]=useState(0);const [mission,setMission]=useState('Build a launch website for my AI startup');return <div className={`mission-window ${compact?'compact':''}`}><aside><div className="window-brand"><Mark/><b>SWARM</b></div><button className="new-mission" onClick={()=>setMission('')}><Plus/> New mission</button><small>START WITH AN IDEA</small>{missions.map((m,i)=><button key={m} className={`side-item ${active===i?'active':''}`} onClick={()=>{setActive(i);setMission(m==='Launch website'?'Build a launch website for my AI startup':m)}}><i/>{m}</button>)}</aside><section className="mission-main"><div className="crumb">Build workspace <em>Project starter</em></div><div className="mission-heading"><small>YOUR NEXT PROJECT</small><h3>What should we build?</h3><p>A plan, reviewed code, and downloadable project files.</p></div><div className="mission-composer"><textarea aria-label="Project idea" value={mission} onChange={e=>setMission(e.target.value)} placeholder="What do you want to build?"/><button aria-label="Open idea in Build" onClick={()=>router.push('/app?mode=build&prompt='+encodeURIComponent(mission))} disabled={!mission.trim()}><ArrowUpRight/></button></div><div className="agent-list">{[['Planner','Organizes the project','P'],['Coder','Creates the files','C'],['Reviewer','Checks and refines','R'],['Finalizer','Packages the project','F']].map(([name,role,mark],i)=><div className="agent-row" key={name}><span className={`agent-avatar a${i}`}>{mark}</span><div><b>{name}</b><small>{role}</small></div></div>)}</div><div className="coordination"><Zap/> You direct the build <span>Download files or ZIP</span></div></section></div> }

function Orbit() { const [hover,setHover]=useState(0); const detail=[['PLAN','Turns the goal into an executable strategy.'],['RESEARCH','Finds the signal.'],['BUILD','Makes it real.'],['DESIGN','Gives it form.'],['TEST','Challenges the result.'],['SHIP','Gets it out the door.']]; return <div className="orbit"><div className="orbit-lines"/><div className="orbit-core"><Mark/><b>SWARM</b><small>{detail[hover][0]}</small></div>{detail.map(([name,desc],i)=><button key={name} className={`orbit-node n${i} ${hover===i?'selected':''}`} onMouseEnter={()=>setHover(i)} onFocus={()=>setHover(i)} onClick={()=>setHover(i)}><b>{name}</b><small>{hover===i?desc:'0'+(i+1)}</small></button>)}</div> }

function Demo() { return <div className="demo"><div className="demo-prompt"><small>YOUR MISSION</small><h3>Build a complete launch website for my new product</h3><CTA href="/app?mode=build&prompt=Build%20a%20complete%20launch%20website%20for%20my%20new%20product">Start this build</CTA></div><div className="demo-progress"><span>The Build workflow</span>{['Plan the project','Create the code','Review the result','Package the files'].map((x,i)=><div key={x}><i>{i+1}</i><span>{x}</span></div>)}</div></div> }

function Landing(){return <><Nav/><CinematicHome/><Footer/><CommandPalette/></>}

function Footer(){return <footer><div><Link href="/" className="brand"><Mark word/><span>SWARM AI</span></Link><p>Think together.<br/>Build together.<br/>Move faster.</p></div><div className="footer-links"><div><b>Product</b><Link href="/agents">Agents</Link><Link href="/platform">Platform</Link><Link href="/cloud">Cloud</Link><Link href="/app">App</Link></div><div><b>Company</b><Link href="/about">About</Link></div><div><b>Resources</b><Link href="/how-it-works">How it works</Link><Link href="/documentation">Documentation</Link><Link href="/changelog">Changelog</Link></div><div><b>Legal</b><Link href="/privacy">Privacy</Link></div></div><small>© 2026 SWARM AI</small></footer> }

const pageCopy:Record<string,string[]>={documentation:['Start with a goal.','Open the app, choose Chat or Build, and describe your task. Auto uses the desktop routing rules to select an available model. Add or remove provider keys in Settings. Build produces reviewed code with individual file and project ZIP downloads.'],privacy:['Your workspace, your provider choices.','Conversations and provider settings sync through your SWARM account. Provider keys are encrypted before storage. Your prompts are sent to the AI provider selected for the request. Deleting a conversation removes its saved messages; removing a provider removes its saved key.'],changelog:['Now in the browser.','SWARM web includes streaming chat, Auto routing, the desktop agent graph in Build mode, persistent conversations, provider settings, and file or ZIP downloads.'],about:['A workspace for making things.','SWARM combines a desktop application and browser workspace. The web app shares the desktop provider adapters and model routing logic, with a focused workflow for generating downloadable code.']};
function StandardPage({ type }: { type:string }) { const data={agents:['MEET THE SWARM.','Specialized capabilities. One coordinated workspace.'],platform:['A WORKSPACE FOR AI TEAMS.','Mission Control, context, and validation in one place.'],cloud:['YOUR WORK DOESN’T STOP WHEN YOU DO.','Follow the swarm from anywhere.'], 'how-it-works':['FROM IDEA TO OUTCOME.','Describe. Decompose. Collaborate. Deliver.'],projects:['PROJECTS.','Everything your swarm is working on.'],activity:['ACTIVITY.','A living record of every mission.'],about:['BUILT FOR THE WORK AHEAD.','SWARM helps teams move from intention to outcome.'],contact:['LET’S BUILD TOGETHER.','Tell us what you are working on.'],documentation:['THE SWARM HANDBOOK.','Learn how missions, agents, and context work together.'],changelog:['WHAT’S NEW.','The latest from SWARM.'],privacy:['PRIVACY.','Your work belongs to you.'],terms:['TERMS.','Simple, clear terms for using SWARM.']}[type]||['SWARM AI.','The workspace for ambitious work.']; return <><Nav/><main className="subpage"><div className="sub-hero"><small className="eyebrow">SWARM AI / {type.toUpperCase()}</small><h1>{data[0]}</h1><p>{data[1]}</p>{type==='agents'?<AgentExplorer/>:type==='platform'?<MissionControl compact/>:type==='cloud'?<><MissionControl compact/><CTA href="/app">Open Cloud</CTA></>:type==='how-it-works'?<Steps/>:type==='projects'||type==='activity'?<CTA>Open your conversations</CTA>:<div className="sub-content"><h2>{pageCopy[type]?.[0]||"One mission. Many minds."}</h2><p>{pageCopy[type]?.[1]||"SWARM brings specialized capabilities into one workspace. Start with a goal, review the result, and download the files."}</p><CTA href="/app">Launch SWARM</CTA></div>}</div></main><Footer/><CommandPalette/></> }
function AgentExplorer(){const [selected,setSelected]=useState(2); return <div className="explorer"><div className="explorer-list">{agents.map(([n,r,m],i)=><button className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={n}><span className={`agent-avatar a${i}`}>{m}</span><b>{n}</b><small>{r}</small></button>)}</div><div className="explorer-detail"><small>AVAILABLE / 0{selected+1}</small><h2>{agents[selected][0].toUpperCase()}</h2><p>{agents[selected][1]}.</p><h4>RESPONSIBILITIES</h4><p>Strategy · context · execution · testing · delivery</p><button onClick={()=>window.location.assign('/app?mode=build')}>Start a build <ArrowUpRight/></button></div></div>}
function Steps(){return <div className="steps">{['DESCRIBE','DECOMPOSE','COLLABORATE','DELIVER'].map((x,i)=><div key={x}><small>0{i+1}</small><h2>{x}</h2><p>{['Tell SWARM what you want.','Break the mission into specialized work.','The planner, coder, and reviewer share the project context.','The swarm reviews and produces the result.'][i]}</p></div>)}</div>}
export default function SwarmSite({ page='home' }: { page?: string }) { return page==='home'?<Landing/>:<StandardPage type={page}/> }
export { MissionControl }
