'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { ArrowUpRight, Check, Command, Menu, Plus, Search, X, Zap } from 'lucide-react'

const logo = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/swarm%20dekstop%20logo-RR8L0vNeB0QTicqTnrvJyYhItqYfVd.png'
const wordmark = 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/swarm%20logo-CJPEzZD66Ozf4Q4zP5RNQ9twYivPH4.png'
const agents = [
  ['Strategist','Shapes the mission','S'],['Researcher','Finds the signal','R'],['Builder','Makes it real','B'],['Designer','Gives it form','D'],['Reviewer','Raises the bar','V'],['Operator','Keeps it moving','O'],
]
const missions = ['Launch website','Research competitors','Build mobile app','Analyze dataset']
function Mark({ word = false }: { word?: boolean }) { return <img className={word ? 'logo wordmark' : 'logo'} src={word ? wordmark : logo} alt="SWARM AI" /> }
function CTA({ children, href='/app', light=false }: { children: React.ReactNode; href?: string; light?: boolean }) { return <Link className={`cta ${light ? 'light' : ''}`} href={href}>{children}<ArrowUpRight /></Link> }

function Nav() {
  const [open,setOpen] = useState(false); const [scrolled,setScrolled] = useState(false)
  useEffect(() => { const onScroll=()=>setScrolled(window.scrollY>20); window.addEventListener('scroll',onScroll,{passive:true}); return()=>window.removeEventListener('scroll',onScroll) },[])
  const links=[['Agents','/agents'],['Platform','/platform'],['Cloud','/cloud'],['How it works','/how-it-works'],['Vision','/vision']]
  return <header className={`nav ${scrolled?'scrolled':''}`}><Link href="/" className="brand"><Mark word /><span>SWARM AI</span></Link><nav className={open?'open':''}>{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href="/login" onClick={()=>setOpen(false)}>Log in</Link><CTA>Launch SWARM</CTA></nav><div className="nav-right"><Link href="/login">Log in</Link><CTA>Launch SWARM</CTA><button className="menu" onClick={()=>setOpen(!open)} aria-label="Open navigation">{open?<X/>:<Menu/>}</button></div></header>
}

function CommandPalette() { const [show,setShow]=useState(false); useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setShow(v=>!v)} }; window.addEventListener('keydown',f); return()=>window.removeEventListener('keydown',f)},[]); if(!show)return null; const items=[['Go to Agents','/agents'],['Go to Platform','/platform'],['Go to Cloud','/cloud'],['Open App','/app'],['View Projects','/projects'],['View Activity','/activity'],['Settings','/settings']]; return <div className="palette-backdrop" onClick={()=>setShow(false)}><div className="palette" onClick={e=>e.stopPropagation()}><div className="palette-search"><Search/><input autoFocus placeholder="Search SWARM"/><kbd>ESC</kbd></div>{items.map(([x,h])=><Link key={h} href={h} onClick={()=>setShow(false)}><Command/><span>{x}</span><ArrowUpRight/></Link>)}</div></div> }

function MissionControl({ compact=false }: { compact?: boolean }) { const [active,setActive]=useState(0); const [running,setRunning]=useState(false); const [done,setDone]=useState(false); const [mission,setMission]=useState('Build a launch website for my AI startup'); useEffect(()=>{if(!running)return;setDone(false);const t=setTimeout(()=>setDone(true),3600);return()=>clearTimeout(t)},[running]); return <div className={`mission-window ${compact?'compact':''}`}><aside><div className="window-brand"><Mark/><b>SWARM</b></div><button className="new-mission" onClick={()=>{setActive(0);setMission('')}}><Plus/> New mission</button><small>RECENT</small>{missions.map((m,i)=><button key={m} className={`side-item ${active===i?'active':''}`} onClick={()=>{setActive(i);setMission(m==='Launch website'?'Build a launch website for my AI startup':m)}}><i/>{m}</button>)}<small className="side-projects">PROJECTS</small>{['SWARM Website','Mobile App','Research'].map(x=><button className="side-item" key={x}><b/> {x}</button>)}</aside><section className="mission-main"><div className="crumb">Mission Control <span>/</span> {missions[active]} <em><i/> 6 agents online</em></div><div className="mission-heading"><small>NEW MISSION</small><h3>{running?'MISSION IN PROGRESS':done?'MISSION COMPLETE':'What should we build?'}</h3><p>{running?'The swarm is coordinating specialized workstreams.':done?'All agents have reviewed and delivered the result.':'Give the swarm a goal. It will take care of the rest.'}</p></div><div className="mission-composer"><textarea value={mission} onChange={e=>setMission(e.target.value)} placeholder="What do you want to build?"/><button onClick={()=>setRunning(true)} disabled={!mission.trim() || running}>{done?<Check/>:<ArrowUpRight/>}</button></div><div className="agent-list">{agents.map(([name,role,mark],i)=><div className="agent-row" key={name}><span className={`agent-avatar a${i}`}>{mark}</span><div><b>{name}</b><small>{running?['Breaking the mission into workstreams…','Gathering context…','Making it real…','Creating the interface…','Checking the result…','Coordinating final delivery…'][i]:role}</small></div><span className={running&&i<5?'status working':'status'}><i/>{done||i>2?'Ready':running?'Working':'Ready'}</span></div>)}</div><div className="coordination"><Zap/> {done?'Mission complete':'Swarm coordination active'} <span>Shared context · 96%</span></div></section></div> }

function Orbit() { const [hover,setHover]=useState(0); const detail=[['PLAN','Turns the goal into an executable strategy.'],['RESEARCH','Finds the signal.'],['BUILD','Makes it real.'],['DESIGN','Gives it form.'],['TEST','Challenges the result.'],['SHIP','Gets it out the door.']]; return <div className="orbit"><div className="orbit-lines"/><div className="orbit-core"><Mark/><b>SWARM</b><small>{detail[hover][0]}</small></div>{detail.map(([name,desc],i)=><button key={name} className={`orbit-node n${i} ${hover===i?'selected':''}`} onMouseEnter={()=>setHover(i)}><b>{name}</b><small>{hover===i?desc:'0'+(i+1)}</small></button>)}</div> }

function Demo() { const [run,setRun]=useState(false); const [step,setStep]=useState(0); useEffect(()=>{if(!run)return; if(step>=6)return; const t=setTimeout(()=>setStep(s=>s+1),650);return()=>clearTimeout(t)},[run,step]); return <div className="demo"><div className="demo-prompt"><small>YOUR MISSION</small><h3>Create a complete launch campaign for my new product</h3><button onClick={()=>{setRun(true);setStep(0)}}>{step>=6?'Replay mission ↻':'Run mission'} <ArrowUpRight/></button></div><div className="demo-progress"><span>Splitting into 6 workstreams</span>{['Strategy','Research','Copy','Design','Engineering','Review'].map((x,i)=><div key={x}><i className={i<step?'complete':i===step?'current':''}>{i<step?<Check/>:i+1}</i><span>{x}</span><b>{i<step?'Complete':i===step?'Working':'Queued'}</b></div>)}</div>{step>=6&&<strong className="mission-complete"><Check/> Mission complete <Link href="/app">View result</Link></strong>}</div> }

function Landing() { return <><Nav/><main className="landing"><section className="hero"><div className="aurora a1"/><div className="aurora a2"/><div className="grain"/><div className="hero-copy"><span className="live-pill"><i/> SWARM AI IS LIVE</span><h1>BUILD ANYTHING<br/><em>WITH A SWARM.</em></h1><p>Give one mission to a team of specialized AI agents.<br/>SWARM plans the work, shares context, builds, reviews, and keeps moving.</p><div className="hero-actions"><CTA>Enter the swarm</CTA><Link href="/agents" className="text-link">Meet the agents <ArrowUpRight/></Link></div></div><MissionControl/></section><section className="section idea"><small className="eyebrow">01 / THE IDEA</small><div className="split"><h2>ONE MISSION.<br/><em>MANY MINDS.</em></h2><div><p className="large">Complex work doesn&apos;t have to happen in a straight line.</p><p>SWARM turns one ambitious goal into a living system of specialists. Each agent brings a point of view. Together, they turn momentum into progress.</p></div></div><Orbit/></section><section className="section mission"><small className="eyebrow">02 / THE MISSION</small><div className="split"><h2>Give the swarm<br/><em>a goal.</em></h2><p>Then get out of the way.<br/>The work is just beginning.</p></div><Demo/></section><section className="section agent-section" id="agents"><small className="eyebrow">03 / THE TEAM</small><div className="split"><h2>Every agent has a job.<br/><em>The swarm has a direction.</em></h2><p>Specialists that think together, not in isolation.</p></div><div className="agent-grid">{agents.map(([n,r,m],i)=><Link href="/agents" className="agent-card" key={n}><span className={`agent-avatar a${i}`}>{m}</span><small>0{i+1}</small><h3>{n}</h3><p>{r}.</p><ArrowUpRight/></Link>)}</div></section><section className="section cloud-preview"><div><small className="eyebrow">04 / THE CLOUD</small><h2>AI work that<br/><em>keeps moving.</em></h2><p>Start on your computer. Follow progress from your phone. Come back to finished work.</p><CTA href="/cloud">Explore SWARM Cloud</CTA></div><div className="phone-card"><span>ACTIVE MISSION</span><strong>Launch website</strong><b>82%</b><div className="progress"><i/></div><hr/><p>6 agents are working in parallel</p></div></section><section className="final"><div><Mark/><h2>GIVE THE MISSION<br/><em>TO THE SWARM.</em></h2><p>Your next idea doesn&apos;t need another chatbot.<br/>It needs a team.</p><CTA light>Enter SWARM AI</CTA></div></section></main><Footer/><CommandPalette/></> }

function Footer(){return <footer><div><Link href="/" className="brand"><Mark word/><span>SWARM AI</span></Link><p>Think together.<br/>Build together.<br/>Move faster.</p></div><div className="footer-links"><div><b>Product</b><Link href="/agents">Agents</Link><Link href="/platform">Platform</Link><Link href="/cloud">Cloud</Link><Link href="/app">App</Link></div><div><b>Company</b><Link href="/vision">Vision</Link><Link href="/about">About</Link><Link href="/contact">Contact</Link></div><div><b>Resources</b><Link href="/how-it-works">How it works</Link><Link href="/documentation">Documentation</Link><Link href="/changelog">Changelog</Link></div><div><b>Legal</b><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div></div><small>© 2026 SWARM AI</small></footer> }

function StandardPage({ type }: { type:string }) { const data:Record<string,[string,string]>={agents:['MEET THE SWARM.','Six specialists. One coordinated mind.'],platform:['A WORKSPACE FOR AI TEAMS.','Mission Control, context, and validation in one place.'],cloud:['YOUR WORK DOESN’T STOP WHEN YOU DO.','Follow the swarm from anywhere.'], 'how-it-works':['FROM IDEA TO OUTCOME.','Describe. Decompose. Collaborate. Deliver.'],vision:['AI SHOULD WORK.','SWARM is a new model for getting ambitious work done.'],projects:['PROJECTS.','Everything your swarm is working on.'],activity:['ACTIVITY.','A living record of every mission.'],about:['BUILT FOR THE WORK AHEAD.','SWARM helps teams move from intention to outcome.'],contact:['LET’S BUILD TOGETHER.','Tell us what you are working on.'],documentation:['THE SWARM HANDBOOK.','Learn how missions, agents, and context work together.'],changelog:['WHAT’S NEW.','The latest from SWARM.'],privacy:['PRIVACY.','Your work belongs to you.'],terms:['TERMS.','Simple, clear terms for using SWARM.']}[type]||['SWARM AI.','The workspace for ambitious work.']; return <><Nav/><main className="subpage"><div className="sub-hero"><small className="eyebrow">SWARM AI / {type.toUpperCase()}</small><h1>{data[0]}</h1><p>{data[1]}</p>{type==='agents'?<AgentExplorer/>:type==='platform'?<MissionControl compact/>:type==='cloud'?<><MissionControl compact/><CTA href="/app">Open Cloud</CTA></>:type==='how-it-works'?<Steps/>:type==='projects'?<ProjectList/>:type==='activity'?<Activity/>:<div className="sub-content"><h2>One mission. Many minds.</h2><p>SWARM brings specialized agents into one clear, collaborative workspace. Explore the product and start a mission when you are ready.</p><CTA href="/app">Launch SWARM</CTA></div>}</div></main><Footer/><CommandPalette/></> }
function AgentExplorer(){const [selected,setSelected]=useState(2); return <div className="explorer"><div className="explorer-list">{agents.map(([n,r,m],i)=><button className={selected===i?'selected':''} onClick={()=>setSelected(i)} key={n}><span className={`agent-avatar a${i}`}>{m}</span><b>{n}</b><small>{r}</small></button>)}</div><div className="explorer-detail"><small>AVAILABLE / 0{selected+1}</small><h2>{agents[selected][0].toUpperCase()}</h2><p>{agents[selected][1]}.</p><h4>RESPONSIBILITIES</h4><p>Strategy · context · execution · testing · delivery</p><button onClick={()=>alert(`${agents[selected][0]} added to mission.`)}>Assign {agents[selected][0]} <ArrowUpRight/></button></div></div>}
function Steps(){return <div className="steps">{['DESCRIBE','DECOMPOSE','COLLABORATE','DELIVER'].map((x,i)=><div key={x}><small>0{i+1}</small><h2>{x}</h2><p>{['Tell SWARM what you want.','Break the mission into specialized work.','Agents communicate and work in parallel.','The swarm reviews and produces the result.'][i]}</p></div>)}</div>}
function ProjectList(){return <div className="project-list">{['SWARM Website','Mobile App','Research','Launch Campaign'].map((x,i)=><Link href="/app" key={x}><span><i/> {x}</span><small>{i<2?'Active':'Ready'} <ArrowUpRight/></small></Link>)}</div>}
function Activity(){return <div className="activity">{['Strategist decomposed mission','Researcher completed market analysis','Designer created interface direction','Builder started implementation','Reviewer started validation'].map((x,i)=><div key={x}><b>12:{42+i*3}</b><span>{x}</span></div>)}</div>}
export default function SwarmSite({ page='home' }: { page?: string }) { return page==='home'?<Landing/>:<StandardPage type={page}/> }
export { MissionControl }
