import Link from 'next/link';
import {ThemeButton} from '@/components/cloud/theme-button';
import {planCatalog} from '@/lib/server/entitlements';
import {Check, Sparkles, Zap} from 'lucide-react';
export const dynamic='force-dynamic';
export default function Pricing(){
 const {free,pro}=planCatalog();
 const price=pro.price===null?'Price unavailable':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(pro.price/100);
 return <main className="cloud-theme pricing-workspace min-h-screen px-5 py-12 md:py-20"><div className="mx-auto max-w-4xl"><div className="pricing-toolbar"><Link href="/" className="text-sm text-slate-500"><img src="/brand/swarm-wordmark.png" alt="SWARM"/>← SWARM home</Link><ThemeButton/></div><header className="my-10 text-center"><h1 className="text-3xl font-semibold tracking-tight md:text-4xl">Choose your SWARM plan</h1><p className="mt-3 text-slate-500">From your first idea to your next big project.</p></header><div className="grid gap-6 md:grid-cols-2">
 <section className="sw-plan flex flex-col p-8"><h2 className="text-2xl font-semibold">Free</h2><div className="my-10"><p className="text-5xl font-semibold">₹0</p><p className="mt-3 text-sm text-slate-500">Start creating with SWARM SWE</p></div><Link href="/app" className="rounded-full border border-slate-200 px-5 py-3 text-center text-sm font-semibold">Start with Free</Link><ul className="mt-8 space-y-5 text-sm">{[`${free.builds} builds per ${free.days} days`,`${free.chats} chats per ${free.days} days`,'Balanced automatic model routing','Chat and build workflows','Web, Windows and Android'].map(v=><li key={v} className="flex gap-3"><Check size={18}/>{v}</li>)}</ul></section>
 <section className="sw-plan sw-plan-featured flex flex-col p-8"><div className="flex justify-between"><h2 className="text-2xl font-semibold">Pro</h2><Sparkles className="text-blue-600" size={23}/></div><div className="my-10"><p className="text-5xl font-semibold">{price}</p><p className="mt-3 text-sm text-slate-500">One payment for {pro.accessDays} days</p></div><Link href="/app/settings?upgrade=pro" className="rounded-full bg-blue-600 px-5 py-3 text-center text-sm font-semibold text-white">Upgrade to Pro</Link><ul className="mt-8 space-y-5 text-sm">{[`${pro.builds??'Pending'} builds per ${pro.days} days`,`${pro.chats??'Pending'} chats per ${pro.days} days`,'SWARM SWE Fast: speed-first routing',`${pro.concurrency} simultaneous requests`,'Manual renewal, no automatic charges'].map(v=><li key={v} className="flex gap-3"><Check size={18}/>{v}</li>)}</ul><p className="mt-8 text-xs leading-5 text-slate-500">Faster routing prioritizes eligible models for speed. Actual response time varies with your task and provider capacity.</p></section>
 </div><div className="mt-8 flex items-start gap-3 rounded-2xl border border-slate-200 bg-white p-5"><Zap className="shrink-0 text-blue-600" size={20}/><p className="text-sm leading-6 text-slate-600">One account across your devices. Review your plan and payment summary before entering secure Cashfree checkout. Premium model availability is shown in your account; no unavailable model is promised with purchase.</p></div></div></main>;
}
