import { useEffect, useState } from 'react';
import { api, type AccountStatus } from '../lib/api';
import { Button } from '../components/ui';
export function AccountSettings(){
  const [status,setStatus]=useState<AccountStatus|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false);
  useEffect(()=>{void api.account.status().then(setStatus).catch(()=>setError('Account status is unavailable.'));return window.swarm.on('account:changed',s=>setStatus(s as AccountStatus));},[]);
  async function action(fn:()=>Promise<AccountStatus>){setPending(true);setError('');try{setStatus(await fn());}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setPending(false);}}
  const user=status?.account;
  return <section className="space-y-5 max-w-xl"><div className="rounded-xl border border-line bg-surface p-5 space-y-4"><div className="flex items-center gap-4"><div aria-hidden className="h-12 w-12 rounded-full bg-blue-100 text-blue-700 grid place-items-center text-lg">{user?.avatar?<img src={user.avatar} alt="" className="h-12 w-12 rounded-full"/>:(user?.name||user?.email||'S').slice(0,1).toUpperCase()}</div><div><h2 className="font-semibold">{status?.connected?(user?.name||'Your SWARM account'):'Welcome back'}</h2><p className="text-sm text-fg-2">{status?.connected?user?.email:'Sign in with your website account.'}</p></div></div><p className="text-sm">{status?.connected?'Account connected':'Not connected'} · {status?.syncing?'Syncing…':status?.lastSync?'Last synced '+new Date(status.lastSync).toLocaleString():'No completed sync yet'}</p><div className="flex flex-wrap gap-2">{status?.connected?<><Button disabled={pending||status.syncing} onClick={()=>void action(api.account.sync)}>Sync now</Button><Button disabled={pending||status.syncing} onClick={()=>void action(api.account.signOut)}>Sign out</Button></>:<Button disabled={pending||status?.connecting} onClick={()=>void action(()=>api.account.signIn('https://www.swarmgpt.online'))}>Sign in to SWARM</Button>}<Button onClick={()=>void api.account.openWebsite()}>Website account</Button></div><p className="text-xs text-fg-3">Account chats, saved provider credentials and supported preferences sync every 30 seconds. Environment credentials, execution permissions and local paths stay on this device. Signing out locks this workspace and preserves its local data.</p></div>{(error||status?.error)&&<p role="alert" className="text-sm text-red-600">{error||status?.error}</p>}</section>;
}
